

library(shiny)
library(purrr)
library(dplyr)
library(shinycssloaders)

# Define UI for random distribution app ----
ui <- fluidPage(

  # App title ----
  titlePanel("Predicts Genes From BLAST Output"),

  # Sidebar layout with input and output definitions ----
  sidebarLayout(

    # Sidebar panel for inputs ----
    sidebarPanel(

      tags$p("This app provides a visual interface for the euPredictR package
              in R. It predicts the protein-coding genes of novel
              eukaroytic organisms based on sequence homology, using raw output
              generated by the Basic Local Alignment
              Search Tool (BLAST)."),

      tags$p("Description: "),

      tags$p("Instructions: Below, enter"),



      # Input: maximum intron length
      numericInput(inputId = "maxIntronLength",
                   label = "Enter max intron length",
                   value = 5,
                   min = 1),

      # remember to include sample datasets for this (and upload their own
      # data) SPecify the type of data, in extdata

      # br() element to introduce extra vertical spacing ----
      br(),

      actionButton(inputId = "button2",
                   label = "Run"),

    ),

    # Main panel for displaying outputs ----
    mainPanel(

      # Output: Tabset w/ plot, summary, and table ----
      tabsetPanel(type = "tabs",
                  tabPanel("Predicted sequence display",
                           tableOutput("predicted_seqs")),

                  tabPanel("Gene Coverage Heatmap",
                           plotOutput("gene_coverage_heatmap") %>%
                             withSpinner(color="#0dc5c1")),

                  tabPanel("Phylogeny Display",

                           br(),

                           selectInput("gene_selection",
                                       "Select a gene",
                                       choices = c("None detected")),


                           plotOutput("phylogeny_display") %>%
                             withSpinner(color="#0dc5c1")

                           )
      )

    )
  )
)

# Define server logic for random distribution app ----
server <- function(input, output, session) {


  startCalculation <- eventReactive(eventExpr = input$button2, {

    euPredictR::build_predictions(raw_blast_list = sample_raw_blast_list,
                                  max_intron_length = input$maxIntronLength,
                                  max_overlap = 30)

  })


  output$gene_coverage_heatmap <- renderPlot({
    if (! is.null(startCalculation))
      euPredictR::gene_coverage_heatmap(predictions = startCalculation())
  })

  observeEvent(input$button2, {
    predictions <- startCalculation()
    total_gene_names <- reduce(lapply(predictions, names), dplyr::union)

    updateSelectInput(session, inputId = "gene_selection",
                      label = "Select a gene",
                      choices = total_gene_names)
  })

  output$phylogeny_display <- renderPlot({
    if (! is.null(startCalculation))
      euPredictR::display_phylogeny(predictions = startCalculation(),
                                    gene_name = input$gene_selection)
  })

  output$predicted_seqs <- renderTable({
    if (! is.null(startCalculation))
      euPredictR::output_predictions(predictions = startCalculation())
  })

}

# Create Shiny app ----
shinyApp(ui, server)
