#' Display a phylogeny of a gene set
#'
#' Sample description
#'
#' @param predictions description
#' @param gene_name description
#'
#' @import msa
#' @import dplyr
#' @import purrr
#' @import phangorn
#' @importFrom Biostrings DNAStringSet
#'
#' @export
#'
display_phylogeny <- function(predictions, gene_name){

  if (!inherits(predictions, "GenePredictions")){
    stop("Incorrect input: 'predictions' must be in GenePredictions
         format and generated by the function build_predictions")
  }

  if (!is.character(gene_name) | length(gene_name) > 1){
    stop("Incorrect input: 'gene_name' must be a single string.")
  }

  # We get the total, unique gene names by the following:
  # 1) lapply applies the names function to each item in 'predictions'
  # to get the gene names present for each species
  # 2) reduce applies the union operator on the gene names until all
  # are concatenated into a single vector
  total_gene_names <- reduce(lapply(predictions, names), dplyr::union)

  if (! gene_name %in% total_gene_names){
    stop("Incorrect input: The string specified to the parameter
         'gene_name' does not correspond to any gene predictions
         in the GenePredictions object passed to the 'predictions'
         parameter.")
  }

  # instantiates an emtpy vector to carry the sequences to be used in the
  # phylogeny (at most, there is one sequence for a gene per species)
  phylo_seqs <- rep(NA, times = length(predictions))

  species_names <- names(predictions)
  names(phylo_seqs) = species_names

  for (i in seq_along(predictions)){

    seq <- predictions[[i]][[gene_name]]

    if (! is.null(seq)){
      phylo_seqs[i] = seq
    }
  }

  # remove species that don't have a predicted coding sequence for the gene of
  # interest
  phylo_seqs <- phylo_seqs[!is.na(phylo_seqs)]

  dna_set <- Biostrings::DNAStringSet(phylo_seqs)

  message("Aligning sequences and constructing phylogeny...
          (ignore messages below, if any are present)")

  phylo_plot <- suppressMessages(msa::msa(dna_set, "ClustalOmega")) %>%
    msaConvert("phangorn::phyDat") %>%
    dist.ml() %>%
    phangorn::upgma() %>%
    plot(main=paste("UPGMA phylogeny based on predicted", gene_name, sep = " "))


  return(phylo_plot)
}
